import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import Script from "next/script";

import { TRPCReactProvider } from "~/trpc/react";
import ThemeToggle from "~/components/theme-toggle";
import React from "react";

// App-wide metadata for the Next.js App Router. This is used to populate <head>
// and can be extended per-route via nested layouts/pages.
export const metadata: Metadata = {
  title: "T3 Stack Test WebApp",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon2.svg" }],
};

// Load the Geist font and expose its CSS variable so Tailwind can use it.
const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    // Attach the Geist font variable and suppress hydration warnings since we mutate the 'dark' class before React hydrates.
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
        {/* Initialize theme as early as possible to prevent flash of incorrect theme (FOUC) */}
        <Script id="theme-init" strategy="beforeInteractive">{
          `try{var d=window.document.documentElement;var s=localStorage.getItem('theme');var m=window.matchMedia('(prefers-color-scheme: dark)');var isDark=s==='dark'||(s!=='light'&&m.matches);if(isDark){d.classList.add('dark')}else{d.classList.remove('dark')}}catch(e){}`
        }</Script>
        {/* Provide tRPC client context to enable hooks in client components */}
        <TRPCReactProvider>{children}</TRPCReactProvider>
        {/* Floating theme toggle so users can switch between light/dark */}
        <ThemeToggle />
      </body>
    </html>
  );
}
